// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 9.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'app_1';

  static const String assets_image_fb_png = 'assets/image/fb.png';
  static const String app_1$assets_image_fb_png = 'packages/app_1/assets/image/fb.png';

  static const String assets_image_gg_png = 'assets/image/gg.png';
  static const String app_1$assets_image_gg_png = 'packages/app_1/assets/image/gg.png';

  static const String assets_image_i0_png = 'assets/image/i0.png';
  static const String app_1$assets_image_i0_png = 'packages/app_1/assets/image/i0.png';

  static const String assets_image_i1_png = 'assets/image/i1.png';
  static const String app_1$assets_image_i1_png = 'packages/app_1/assets/image/i1.png';

  static const String assets_image_i2_png = 'assets/image/i2.png';
  static const String app_1$assets_image_i2_png = 'packages/app_1/assets/image/i2.png';

  static const String assets_image_i3_png = 'assets/image/i3.png';
  static const String app_1$assets_image_i3_png = 'packages/app_1/assets/image/i3.png';

  static const String assets_image_ig_png = 'assets/image/ig.png';
  static const String app_1$assets_image_ig_png = 'packages/app_1/assets/image/ig.png';

  static const String assets_image_login1_png = 'assets/image/login1.png';
  static const String app_1$assets_image_login1_png = 'packages/app_1/assets/image/login1.png';

  static const String assets_image_signUp1_png = 'assets/image/signUp1.png';
  static const String app_1$assets_image_signUp1_png = 'packages/app_1/assets/image/signUp1.png';
}
