// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 26.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'app_1';

  static const String assets_image_Go_back_svg = 'assets/image/Go-back.svg';
  static const String app_1$assets_image_Go_back_svg = 'packages/app_1/assets/image/Go-back.svg';

  static const String assets_image_avatar_png = 'assets/image/avatar.png';
  static const String app_1$assets_image_avatar_png = 'packages/app_1/assets/image/avatar.png';

  static const String assets_image_avatar1_png = 'assets/image/avatar1.png';
  static const String app_1$assets_image_avatar1_png = 'packages/app_1/assets/image/avatar1.png';

  static const String assets_image_courses_svg = 'assets/image/courses.svg';
  static const String app_1$assets_image_courses_svg = 'packages/app_1/assets/image/courses.svg';

  static const String assets_image_email_svg = 'assets/image/email.svg';
  static const String app_1$assets_image_email_svg = 'packages/app_1/assets/image/email.svg';

  static const String assets_image_fb_png = 'assets/image/fb.png';
  static const String app_1$assets_image_fb_png = 'packages/app_1/assets/image/fb.png';

  static const String assets_image_gg_png = 'assets/image/gg.png';
  static const String app_1$assets_image_gg_png = 'packages/app_1/assets/image/gg.png';

  static const String assets_image_human_svg = 'assets/image/human.svg';
  static const String app_1$assets_image_human_svg = 'packages/app_1/assets/image/human.svg';

  static const String assets_image_i0_png = 'assets/image/i0.png';
  static const String app_1$assets_image_i0_png = 'packages/app_1/assets/image/i0.png';

  static const String assets_image_i1_png = 'assets/image/i1.png';
  static const String app_1$assets_image_i1_png = 'packages/app_1/assets/image/i1.png';

  static const String assets_image_i2_png = 'assets/image/i2.png';
  static const String app_1$assets_image_i2_png = 'packages/app_1/assets/image/i2.png';

  static const String assets_image_i3_png = 'assets/image/i3.png';
  static const String app_1$assets_image_i3_png = 'packages/app_1/assets/image/i3.png';

  static const String assets_image_ig_png = 'assets/image/ig.png';
  static const String app_1$assets_image_ig_png = 'packages/app_1/assets/image/ig.png';

  static const String assets_image_img_product_png = 'assets/image/img_product.png';
  static const String app_1$assets_image_img_product_png = 'packages/app_1/assets/image/img_product.png';

  static const String assets_image_login1_png = 'assets/image/login1.png';
  static const String app_1$assets_image_login1_png = 'packages/app_1/assets/image/login1.png';

  static const String assets_image_look_svg = 'assets/image/look.svg';
  static const String app_1$assets_image_look_svg = 'packages/app_1/assets/image/look.svg';

  static const String assets_image_next_icon_svg = 'assets/image/next_icon.svg';
  static const String app_1$assets_image_next_icon_svg = 'packages/app_1/assets/image/next_icon.svg';

  static const String assets_image_notification_svg = 'assets/image/notification.svg';
  static const String app_1$assets_image_notification_svg = 'packages/app_1/assets/image/notification.svg';

  static const String assets_image_profile_svg = 'assets/image/profile.svg';
  static const String app_1$assets_image_profile_svg = 'packages/app_1/assets/image/profile.svg';

  static const String assets_image_result_ui_1_png = 'assets/image/result_ui_1.png';
  static const String app_1$assets_image_result_ui_1_png = 'packages/app_1/assets/image/result_ui_1.png';

  static const String assets_image_result_ui_2_png = 'assets/image/result_ui_2.png';
  static const String app_1$assets_image_result_ui_2_png = 'packages/app_1/assets/image/result_ui_2.png';

  static const String assets_image_setting_screen_png = 'assets/image/setting_screen.png';
  static const String app_1$assets_image_setting_screen_png = 'packages/app_1/assets/image/setting_screen.png';

  static const String assets_image_signUp1_png = 'assets/image/signUp1.png';
  static const String app_1$assets_image_signUp1_png = 'packages/app_1/assets/image/signUp1.png';

  static const String assets_image_wheel_1_svg = 'assets/image/wheel 1.svg';
  static const String app_1$assets_image_wheel_1_svg = 'packages/app_1/assets/image/wheel 1.svg';

  static const String assets_image_your_course_1_png = 'assets/image/your_course_1.png';
  static const String app_1$assets_image_your_course_1_png = 'packages/app_1/assets/image/your_course_1.png';

  static const String assets_image_your_course_2_png = 'assets/image/your_course_2.png';
  static const String app_1$assets_image_your_course_2_png = 'packages/app_1/assets/image/your_course_2.png';
}
